use stellar_xdr::curr::TypeVariant;

/// Generates a Go file that contains the types for the XDR-JSON schema as
/// constants.
fn main() {
    println!("// Code generated by scripts/generate-types. DO NOT EDIT.");
    println!();
    println!("package xdrjson");
    println!();
    println!("type XdrType string");
    println!();
    println!("const (");
    for typ in TypeVariant::variants() {
        let name = typ.name();
        println!("    {name} XdrType = \"{name}\"");
    }
    println!(")");
}
